### ISSUE TITLE
Pantry Cards do not contain zipcodes

### ISSUE THREAD

**Issue by legitmaxwu** [code-and-affect/food-pantries-map#4]
![image](https://user-images.githubusercontent.com/19853022/57999421-384a9c00-7a8a-11e9-9933-637692358053.png)

Pantry Cards should have zip codes in them.

**Comment by sjiang647** [comment]
zip codes added on branch steve ( 1 line in pantrycard.js )
![image](https://user-images.githubusercontent.com/15708812/58036258-85a52880-7adf-11e9-98d2-323f957729f6.png)
